### ISSUE TITLE
Feature: User can view the homepage where they can see existing characters (if any) and initiate the character creation process as well.

### ISSUE THREAD

**Issue by jonahp001** [jonahp001/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-03-01 at 10 12 10 AM](https://user-images.githubusercontent.com/117235085/222225957-7c9421f8-5d17-4edf-bc09-5cd22d0d7c0b.png)
![Screenshot 2023-03-01 at 10 11 58 AM](https://user-images.githubusercontent.com/117235085/222225969-f2bb434f-dc04-4fa7-adb7-e7c60dde017d.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write the HTML and CSS to reflect the figma design.
- [x] Design responsive CSS that adapts from mobile to desktop via @media rule
- [x] Add a 'click' event listener to the "START" button that view swaps to the character creation page.
- [x] leave gallery at the bottom empty for now-- address this section later after character creation and saving characters.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
